apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: rails-scaler
spec:
  scaleTargetRef: 
    kind: Deployment
    name: rails
    apiVersion: apps/v1beta1
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
